name: CI

on:
  push:
    branches: [ master, 'feature/**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
        
